/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_8y9;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *Interfaz grafica para ordenar
 * @author Juan Carlos Huerta Llamas
 */
public class Ordenacion extends javax.swing.JFrame {
    Quicksort qs;
    Shellsort ss;
    Insercion insercion;
    Seleccion seleccion;
    Paises[] arreglo;
    InfoPaises info;
     Tiempo tiempo;
     
    /**
     * Creates new form Ordenacion
     */
    public Ordenacion() {
        initComponents();
        qs = new Quicksort();
        ss= new Shellsort();
        insercion=new Insercion();
        seleccion= new Seleccion();
        arreglo = new Paises[245];
        info = new InfoPaises();
        tiempo = new Tiempo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        op1 = new javax.swing.JComboBox();
        op2 = new javax.swing.JComboBox();
        op3 = new javax.swing.JComboBox();
        op4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        texto4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ordenacion");

        op1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Pais", "Continente", "Capital" }));

        op2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Pais", "Continente", "Capital" }));

        op3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Pais", "Continente", "Capital" }));

        op4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Pais", "Continente", "Capital" }));

        texto1.setColumns(20);
        texto1.setRows(5);
        jScrollPane1.setViewportView(texto1);

        texto2.setColumns(20);
        texto2.setRows(5);
        jScrollPane2.setViewportView(texto2);

        texto3.setColumns(20);
        texto3.setRows(5);
        jScrollPane3.setViewportView(texto3);

        texto4.setColumns(20);
        texto4.setRows(5);
        jScrollPane4.setViewportView(texto4);

        jButton1.setText("Quicksort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Shellsort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Insercion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Seleccion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262)
                .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(356, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Inicializando");
        String t = "";
        info.Alta(arreglo);
        System.out.println("Se lleno");
        if (op1.getSelectedIndex() == 0) {  
            try {
                tiempo.Inicio();

                qs.Quicksortnumeros(arreglo, 0, arreglo.length - 1);

                t = tiempo.Terminar();
                System.out.println("ordenado");
                
                String cadena = "QuickSort\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString()+"\n";
                }
                texto1.setText(cadena);

            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if(op1.getSelectedIndex()==1){
            try {
                tiempo.Inicio();
                qs.Quicksortauxiliar2(arreglo);
                t = tiempo.Terminar();
               
                System.out.println("Ordenado");
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            String cadena = "QuickSort\n";
            cadena += t + "\n";
            int j;
            int i = j = 0;
            for (Paises ar : arreglo) {
                cadena += ar.toString()+"\n";
            }
            texto1.setText(cadena);
        }else if(op1.getSelectedIndex()==2){
            try {
                tiempo.Inicio();
                qs.Quicksortauxiliar(arreglo);
                t = tiempo.Terminar();
               
                System.out.println("Ordenado");
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            String cadena = "QuickSort\n";
            cadena += t + "\n";
            int j;
            int i = j = 0;
            for (Paises ar : arreglo) {
                cadena += ar.toString()+"\n";
            }
            texto1.setText(cadena);
        }else if(op1.getSelectedIndex()==3){
            try {
                tiempo.Inicio();
                qs.Quicksortauxiliar3(arreglo);
                t = tiempo.Terminar();
               
                System.out.println("Ordenado");
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            String cadena = "QuickSort\n";
            cadena += t + "\n";
            int j;
            int i = j = 0;
            for (Paises ar : arreglo) {
                cadena += ar.toString()+"\n";
            }
            texto1.setText(cadena);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Inicializando");
        String t = "";
        info.Alta(arreglo);
        System.out.println("Se Lleno");
        if (op2.getSelectedIndex() == 0) {
            try {
                tiempo.Inicio();
                ss.Shellsortnumeros(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "ShellSort\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto2.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else if(op2.getSelectedIndex()==1){
            try {
                tiempo.Inicio();
                ss.ShellsortPaises(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "ShellSort\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto2.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(op2.getSelectedIndex()==2){
            try {
                tiempo.Inicio();
                ss.ShellsortContinente(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "ShellSort\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto2.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(op2.getSelectedIndex()==3){
            try {
                tiempo.Inicio();
                ss.ShellsortCapital(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "ShellSort\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto2.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Inicializando");
        String t = "";
        info.Alta(arreglo);
        System.out.println("Se lleno");
        if (op3.getSelectedIndex() == 0) {
            try {
                tiempo.Inicio();

                insercion.Insercionnumeros(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "Insercion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto3.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if(op3.getSelectedIndex()==1){
            try {
                tiempo.Inicio();
                insercion.InsercionPais(arreglo);
                t = tiempo.Terminar();
                System.out.println("ordenado");

                String cadena = "Insercion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto3.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(op3.getSelectedIndex()==2){
            try {
                tiempo.Inicio();
                insercion.InsercionContinente(arreglo);
                t = tiempo.Terminar();
                System.out.println("ordenado");

                String cadena = "Insercion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto3.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(op3.getSelectedIndex()==3){
            try {
                tiempo.Inicio();
                insercion.InsercionCapital(arreglo);
                t = tiempo.Terminar();
                System.out.println("ordenado");

                String cadena = "Insercion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto3.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.out.println("Inicializando");
        String t = "";
        info.Alta(arreglo);
        System.out.println("Se lleno");
        if (op4.getSelectedIndex() == 0) {

            try {
                tiempo.Inicio();
                seleccion.Seleccionnumeros(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "Seleccion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto4.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if(op4.getSelectedIndex()==1){
            try {
                tiempo.Inicio();

                seleccion.SeleccionPais(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "Seleccion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto4.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(op4.getSelectedIndex()==2){
            try {
                tiempo.Inicio();

                seleccion.SeleccionContinente(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "Seleccion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto4.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(op4.getSelectedIndex()==3){
            try {
                tiempo.Inicio();

                seleccion.SeleccionCapital(arreglo);
                t = tiempo.Terminar();
                System.out.println("Ordenado");

                String cadena = "Seleccion\n";
                cadena += t + "\n";
                int j;
                int i = j = 0;
                for (Paises ar : arreglo) {
                    cadena += ar.toString() + "\n";
                }
                texto4.setText(cadena);
            } catch (InterruptedException ex) {
                Logger.getLogger(Ordenacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox op1;
    private javax.swing.JComboBox op2;
    private javax.swing.JComboBox op3;
    private javax.swing.JComboBox op4;
    private javax.swing.JTextArea texto1;
    private javax.swing.JTextArea texto2;
    private javax.swing.JTextArea texto3;
    private javax.swing.JTextArea texto4;
    // End of variables declaration//GEN-END:variables
}
